# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_model <- function(N, I0, dt, end_time, gamma, R0) {
    .Call(`_individualtest_run_model`, N, I0, dt, end_time, gamma, R0)
}

