# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_model <- function() {
    .Call('_individualtest_create_model', PACKAGE = 'individualtest')
}

run_model <- function(m) {
    invisible(.Call('_individualtest_run_model', PACKAGE = 'individualtest', m))
}

