# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

birth_process <- function(variable, event, birth_rate) {
    .Call(`_individualtest_birth_process`, variable, event, birth_rate)
}

infection_process <- function(variable, beta, N, dt) {
    .Call(`_individualtest_infection_process`, variable, beta, N, dt)
}

recovery_process <- function(variable, event, gamma, dt) {
    .Call(`_individualtest_recovery_process`, variable, event, gamma, dt)
}

death_process <- function(variable, event, death_rate) {
    .Call(`_individualtest_death_process`, variable, event, death_rate)
}

run_model <- function(N, I0, dt, end_time, gamma, R0, birth_rate, death_rate) {
    .Call(`_individualtest_run_model`, N, I0, dt, end_time, gamma, R0, birth_rate, death_rate)
}

